version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0.2-focal
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB:-comment_service}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-!changeMe!}
    volumes:
      - db_data:/data/db

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME : ${MONGO_USER:-mongo}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS:-!changeMe!}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    ports:
      - '6082:8081'
volumes:
  db_data: